[package]
authors = ["jD91mZM2 <me@krake.one>"]
name = "termplay"
version = "0.1.0"
[dependencies]
image = "0.18.0"

[dependencies.termplay]
default-features = false
version = "2.0.2"

[lib]
crate-type = ["cdylib"]
