[package]
authors = ["jD91mZM2 <me@krake.one>"]
name = "wasm"
version = "0.1.0"

[dependencies]
image = "0.19.0"
insult = "2.0.3"
lci = "0.1.8"
rand_core = "0.2.1"

[dependencies.crappy-chess-minimax]
git = "https://github.com/jD91mZM2/crappy-chess-minimax"

[dependencies.termplay]
default-features = false
version = "2.0.5"

[lib]
crate-type = ["cdylib"]
