[package]
name = "wasm"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]

[dependencies]
image = "0.18.0"
insult = "2.0.1"
rand = "0.4.2"

[dependencies.crappy-chess-minimax]
git = "https://github.com/jD91mZM2/crappy-chess-minimax"

[dependencies.lci]
git = "https://github.com/jD91mZM2/rust-lci"

[dependencies.termplay]
default-features = false
version = "2.0.2"

[lib]
crate-type = ["cdylib"]
