[package]
name = "crappy-chess-minimax-wasm"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]

[dependencies.crappy-chess-minimax]
#git = "https://github.com/jD91mZM2/crappy-chess-minimax"
path = "/home/jD91mZM2/Coding/Rust/crappy-chess-minimax"

[lib]
crate-type = ["cdylib"]
